keys:
  - &yaro 8a676fdcaad929184299d020151a8f0401fb2e85
  - &loki age1ffxn4wts02f42xrqrn0lq087fe5mwpkd08w9lsj8sqspmvxam9vqjettz9
  - &loki-game age1ffxn4wts02f42xrqrn0lq087fe5mwpkd08w9lsj8sqspmvxam9vqjettz9
creation_rules:
  - path_regex: ./[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *yaro
      age:
      - *loki
      - *loki-game
