keys:
  - &admin_yaro 8a676fdcaad929184299d020151a8f0401fb2e85
  - &desktop_loki age1p3cfga47d7jj0xxrggfu6pggptdajtlqgk3294j3antxe4pwas9svv7jlt
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_yaro
      age:
      - *desktop_loki